### ISSUE TITLE
Why don't I see this action in the Marketplace search results  for the query "pycodestyle" (but I see its page there by the direct link)?

### ISSUE THREAD

**Issue by KOLANICH** [andymckay/pycodestyle-action#7]
https://github.com/marketplace?type=actions&query=pycodestyle

How many other actions are not shown there this way (and so how many wheels are reinvented?) Could you as an action dev contact GH about that?

**Comment by andymckay** [comment]
🤷🏾 don't know, but I don't work at GitHub anymore. This was likely because I added this so early on in the Actions cycle and things have likely changed since then.
